---
# default vcms host vars


hostname: videos.jornada.com.mx

storage_dirs:
  - name: media
    path: /mnt/media
    backend: FileSystem

  - name: originales
    path: /mnt/originales
    backend: FileSystem

  - name: temporales
    path: /mnt/temporales
    backend: FileSystem


nginx_ssl_certificate: false
nginx_ssl_certificate_key: false

vcms_apps:
  - name: vcms
    title: VCMS
    admin_host: vcms-dev.jornada.com.mx
    admin_url: https://vcms-dev.jornada.com.mx/
    frontend_url: https://vcms-dev.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ ' http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    redis_db: 1