---
# default vcms host vars


hostname: vcms-dev.openmultimedia.biz

ssl_enabled: false

mounts: []

storage_dirs:
  - {name: media, backend: FileSystem, path: /mnt/media}
  - {name: originales, backend: FileSystem, path: /mnt/originales}
  - {name: temporales, backend: FileSystem, path: /mnt/temporales}

vcms_apps:
  - name: vcms
    title: VCMS
    admin_host: vcms-dev.openmultimedia.biz
    admin_url: http://vcms-dev.openmultimedia.biz/
    frontend_url: http://vcms-dev-frontend.openmultimedia.biz
    x_frame_allow_from: http://vcms-dev-frontend.openmultimedia.biz http://vcms-dev.openmultimedia.biz
    language_code: es
    redis_db: 1