---
# videos.jornada.com.mx host vars


hostname: videos.jornada.com.mx

network:
  - iface: ens3
    type: static
    conf:
      address: 172.16.20.40
      netmask: 255.255.255.0
      network: 172.16.20.0
      broadcast: 172.16.20.255
      gateway: 172.16.20.254
      dns-nameservers: 172.16.20.254
      dns-search: jornada.com.mx

ssl_enabled: true
nginx_ssl_certificate: lajornada/jornada.com.mx.crt
nginx_ssl_certificate_key: lajornada/jornada.com.mx.key

mounts:
    - path: '/mnt'
      src: 'UUID=a891a365-762e-467f-bcee-33db2193d8aa'
      type: 'ext4'
      opts: 'noatime,errors=remount-ro'

storage_dirs:
  - {name: media, backend: FileSystem, path: /mnt/media}
  - {name: originales, backend: FileSystem, path: /mnt/originales}
  - {name: temporales, backend: FileSystem, path: /mnt/temporales}

vcms_apps:
  - name: lajornadavideos
    title: La Jornada Videos
    admin_host: videosadmin.jornada.com.mx
    admin_url: https://videosadmin.jornada.com.mx/
    frontend_url: https://videos.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    redis_db: 1

  - name: ciencias
    title: La Jornada Ciencias Videos
    admin_host: ciencias.jornada.com.mx
    admin_url: https://cienciasadmin.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    frontend_url: false
    language_code: es
    redis_db: 2

  - name: wikileaks
    title: La Jornada wikileaks Videos
    admin_host: wikileaksadmin.jornada.com.mx
    admin_url: https://wikileaksadmin.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    frontend_url: false
    redis_db: 3

  - name: letraese
    title: La Jornada LetraEse Videos
    admin_host: letraese.jornada.com.mx
    admin_url: https://letraeseadmin.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    frontend_url: false
    redis_db: 4

  - name: ojarasca
    title: La Jornada Ojarasca Videos
    admin_host: ojarascaadmin.jornada.com.mx
    admin_url: https://ojarascaadmin.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    frontend_url: false
    redis_db: 5

  - name: semanal
    title: La Jornada Semanal Videos
    admin_host: semanal.jornada.com.mx
    admin_url: https://semanaladmin.jornada.com.mx/
    x_frame_allow_from: http://www.jornada.unam.mx/ https://editonline.jornada.com.mx/ http://ojarasca.jornada.com.mx/ http://semanal.jornada.com.mx/ http://letraese.jornada.com.mx/ http://ciencias.jornada.com.mx/ http://wikileaks.jornada.com.mx/ http://staging.jornada.com.mx/
    language_code: es
    frontend_url: false
    redis_db: 6
    
