---
# solr role tasks

# APT packages
- name: Install APT packages
  apt: pkg={{ item }}
  with_items:
    - solr-jetty
  tags:
    - packages

- name: Ensure jetty is running
  service: name=jetty8 state=started