---
- hosts: default
  vars:
    - vcms_apps:
      - lajornadavideos
      - ciencias
      - wikileaks
  tasks:
    - name: Set hostname
      hostname: name=vcm-dev
    - name: Update all packages to latest version
      apt: update_cache=yes upgrade=dist

    - name: Add PPA repository for FFmpeg and codec libraries
      apt_repository: repo='ppa:mc3man/trusty-media' update_cache=yes

    - name: Set MySQL root password in case of installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='pass' vtype='password'

    - name: Confirm MySQL root password in case of installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='pass' vtype='password'

    - name: Install required APT packages
      apt: pkg={{ item }}
      with_items:
        - python-virtualenv
        - python3-pip
        - python-memcache
        - redis-server
        - libjpeg-dev
        - git
        - solr-jetty
        - python-dev
        - libyaml-dev
        - imagemagick
        - mysql-server
        - libmysqlclient-dev
        - ffmpeg
        - x264
        - fdkaac-encoder
        - python-mysqldb
        - uwsgi
        - uwsgi-plugin-python

    - name: NGINX | Adding NGINX signing key
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Adding sources.list deb url for NGINX
      lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
      register: nginx_deburl
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Adding sources.list deb-src url for NGINX
      lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
      register: nginx_debsrcurl
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Updating apt cache
      apt: update_cache=yes
      when: nginx_deburl.changed or nginx_debsrcurl.changed
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Installing NGINX
      apt: pkg=nginx state=latest
      tags: ['nginx', 'app', 'install']

    - name: Create storage directories
      file: path={{ item }} state=directory mode=0777 follow=True
      tags: ['storage', 'app']
      with_items:
        - /mnt/lajornadavideos_storage/media/hls
        - /mnt/lajornadavideos_storage/media/dash
        - /mnt/lajornadavideos_storage/media/original
        - /mnt/lajornadavideos_storage/media/images
        - /mnt/lajornadavideos_storage/media/sprites
        - /mnt/lajornadavideos_storage/media/videos
        - /mnt/lajornadavideos_storage/static/lajornadavideos
        - /mnt/lajornadavideos_storage/static/vcms
        - /mnt/lajornadavideos_storage/tmp/img
        - /mnt/lajornadavideos_storage/tmp/mp4
        - /mnt/lajornadavideos_storage/tmp/original
        - /mnt/lajornadavideos_storage/tmp/status
        - /var/log/vcms
        - /var/log/lajornadavideos

    - name: Copy  web server configuration file
      copy: src=etc/nginx.conf dest=/etc/nginx.conf
      tags: ['nginx', 'app']
      notify:
        - restart nginx

    # App server
    - name: you-get installed
      command: pip3 install you-get creates="/usr/local/bin/you-get"
      tags: ['python', 'app', 'install']

    - name: vcms python requirements installed
      pip: requirements=/vagrant/vcms/vcms/requirements.txt state=latest

    - name: databases created
      mysql_db: name={{ item }} login_user=root login_password=pass state=present
      register: database
      tags: ['python', 'app', 'database']
      with_items: "{{ vcms_apps }}"

    - name: databases migrated
      django_manage: command=migrate app_path=/vagrant/vcms settings=vcms.settings_{{ item }}
      tags: ['python', 'app', 'database', 'django']
      with_items: "{{ vcms_apps }}"

    # - name: vcms initial fixtures loaded if database changed
    #   django_manage: command=loaddata app_path=/vagrant/video_site fixtures='' settings=vcms.settings_{{ item }}
    #   when: database.changed
    #   with_items: {{ vcms_apps }}

    - name: vcms static files collected
      django_manage: command=collectstatic app_path=/vagrant/vcms settings=vcms.settings_{{ item }}
      tags: ['python', 'app', 'storage', 'django', 'collectstatic']
      with_items: "{{ vcms_apps }}"

    - name: vcm uWSGI configuration copied
      template: src=etc/uwsgi-vcms.ini.j2 dest=/etc/uwsgi/apps-enabled/vcms_{{ item }}.ini
      with_items: "{{ vcms_apps }}"
      tags: ['uwsgi', 'app', 'backend']
      notify:
        - restart uwsgi

    - name: vcm nginx configuration copied
      template: src=etc/nginx-vcms.conf.j2 dest=/etc/nginx/conf.d/vcms_{{ item }}.conf
      with_items: "{{ vcms_apps }}"
      tags: ['nginx', 'app']
      notify:
        - restart nginx

    # La Jornada Videos

    - name: Install lajornadavideos python requirements
      pip: requirements=/vagrant/vcms/lajornadavideos/requirements.txt state=latest
      tags: ['python', 'app', 'install', 'frontend']

    - name: Collect lajornadavideos static files
      django_manage: command=collectstatic app_path=/vagrant/vcms settings=lajornadavideos.settings
      tags: ['python', 'app', 'install', 'frontend', 'collectstatic']

    - name: Copy uWSGI lajornadavideos applicaiton configuration file
      copy: src=etc/uwsgi-lajornadavideos.ini dest=/etc/uwsgi/apps-enabled/lajornadavideos.ini
      tags: ['uwsgi', 'app', 'install', 'frontend']
      notify:
        - restart uwsgi

    - name: lajornadavideos nginx config updated
      template: src=etc/nginx-lajornadavideos.conf.j2 dest=/etc/nginx/conf.d/lajornadavideos.conf
      tags: ['nginx', 'app', 'frontend']
      notify:
        - restart nginx

    # System 

    # - name: Add supervisor upstart script
    #   copy: src=etc/upstart-supervisor.conf dest=/etc/init/supervisor.conf
    #   notify:
    #     - reload upstart configuration

    - name: Ensure uWSGI is running
      service: name=uwsgi state=started

    - name: Ensure NGINX is running
      service: name=nginx state=started

    # - name: Ensure supervisor is running
    #   service: name=supervisor state=started


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart uwsgi
      service: name=uwsgi state=restarted

    - name: reload upstart configuration
      command: initctl reload-configuration
