---
- hosts: default

  vars:

    - vcms_apps:
      - lajornadavideos
      - ciencias
      - wikileaks

    - media_dirs:
      - mp4
      - webm
      - hls
      - dash
      - sprites
      - images
      - captions

  tasks:
    - name: hostname set
      hostname: name=vcm-dev

    - name: APT packages updated at latest version
      apt: update_cache=yes upgrade=dist

    - name: PPA repository for FFmpeg and codec libraries added
      apt_repository: repo='ppa:mc3man/trusty-media' update_cache=yes

    - name: Set MySQL root password in case of installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='pass' vtype='password'

    - name: Confirm MySQL root password in case of installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='pass' vtype='password'

    - name: Required APT packages installed
      apt: pkg={{ item }}
      with_items:
        - fdkaac-encoder
        - ffmpeg
        - git
        - imagemagick
        - libjpeg-dev
        - libmysqlclient-dev
        - libyaml-dev
        - mysql-server
        - python-dev
        - python-memcache
        - python-mysqldb
        - python-virtualenv
        - python3-pip
        - redis-server
        - solr-jetty
        - uwsgi
        - uwsgi-plugin-python
        - x264

    - name: NGINX | Adding NGINX signing key
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Adding sources.list deb url for NGINX
      lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
      register: nginx_deburl
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Adding sources.list deb-src url for NGINX
      lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
      register: nginx_debsrcurl
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Updating apt cache
      apt: update_cache=yes
      when: nginx_deburl.changed or nginx_debsrcurl.changed
      tags: ['nginx', 'app', 'install']

    - name: NGINX | Installing NGINX
      apt: pkg=nginx state=latest
      tags: ['nginx', 'app', 'install']

    - name: Create log directory
      file: path=/var/log/vcms state=directory owner=nginx mode=0777 follow=True

    - name: Create storage directories
      file: path=/mnt/media_storage/{{ item.0 }}/{{ item.1 }} state=directory owner=nginx mode=0777 follow=True
      tags: ['storage', 'app']
      with_nested:
        - "{{ vcms_apps }}"
        - "{{ media_dirs }}"

    - name: Copy  web server configuration file
      copy: src=etc/nginx.conf dest=/etc/nginx.conf
      tags: ['nginx', 'app']
      notify:
        - restart nginx

    # App server
    - name: latest you-get installed
      command: pip3 install --upgrade you-get creates="/usr/local/bin/you-get"
      tags: ['python', 'app', 'install']

    - name: vcms python requirements installed
      pip: requirements=/vagrant/vcms/vcms/requirements.txt state=latest

    - name: databases created
      mysql_db: name={{ item }} login_user=root login_password=pass state=present
      register: database
      tags: ['python', 'app', 'database']
      with_items: "{{ vcms_apps }}"

    - name: databases migrated
      django_manage: command=migrate app_path=/vagrant/vcms settings=vcms.settings_{{ item }}
      become: true
      become_user: nginx
      tags: ['python', 'app', 'database', 'django']
      with_items: "{{ vcms_apps }}"

    - name: Iniial users created
      django_manage: command="createsuperuser --noinput --username=admin --email=admin@example.com" app_path=/vagrant/vcms settings=vcms.settings_{{ item }}
      become: true
      become_user: nginx
      tags: ['app', 'database', 'django']
      when: database.changed
      with_items: "{{ vcms_apps }}"

    # - name: vcms initial fixtures loaded if database changed
    #   django_manage: command=loaddata app_path=/vagrant/video_site fixtures='' settings=vcms.settings_{{ item }}
    #   when: database.changed
    #   with_items: {{ vcms_apps }}

    - name: vcms static files collected
      django_manage: command=collectstatic app_path=/vagrant/vcms settings=vcms.settings_{{ item }}
      tags: ['python', 'app', 'storage', 'django', 'collectstatic']
      with_items: "{{ vcms_apps }}"

    - name: vcm uWSGI configuration copied
      template: src=etc/uwsgi-vcms.ini.j2 dest=/etc/uwsgi/apps-enabled/vcms_{{ item }}.ini
      with_items: "{{ vcms_apps }}"
      tags: ['uwsgi', 'app', 'backend']
      notify:
        - restart uwsgi

    - name: vcm nginx configuration copied
      template: src=etc/nginx-vcms.conf.j2 dest=/etc/nginx/conf.d/vcms_{{ item }}.conf
      with_items: "{{ vcms_apps }}"
      tags: ['nginx', 'app']
      notify:
        - restart nginx

    # La Jornada Videos

    - name: Install lajornadavideos python requirements
      pip: requirements=/vagrant/vcms/lajornadavideos/requirements.txt state=latest
      tags: ['python', 'app', 'install', 'frontend']

    - name: Collect lajornadavideos static files
      django_manage: command=collectstatic app_path=/vagrant/vcms settings=lajornadavideos.settings
      tags: ['python', 'app', 'install', 'frontend', 'collectstatic']

    - name: Copy uWSGI lajornadavideos applicaiton configuration file
      copy: src=etc/uwsgi-lajornadavideos.ini dest=/etc/uwsgi/apps-enabled/lajornadavideos.ini
      tags: ['uwsgi', 'app', 'install', 'frontend']
      notify:
        - restart uwsgi

    - name: lajornadavideos nginx config updated
      template: src=etc/nginx-lajornadavideos.conf.j2 dest=/etc/nginx/conf.d/lajornadavideos.conf
      tags: ['nginx', 'app', 'frontend']
      notify:
        - restart nginx

    # System 

    # - name: Add supervisor upstart script
    #   copy: src=etc/upstart-supervisor.conf dest=/etc/init/supervisor.conf
    #   notify:
    #     - reload upstart configuration

    - name: Ensure uWSGI is running
      service: name=uwsgi state=started

    - name: Ensure NGINX is running
      service: name=nginx state=started

    # - name: Ensure supervisor is running
    #   service: name=supervisor state=started


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart uwsgi
      service: name=uwsgi state=restarted

    - name: reload upstart configuration
      command: initctl reload-configuration
