---
# ffmpeg role tasks

# see https://trac.ffmpeg.org/wiki/UbuntuCompilationGuide

- name: Install APT packages
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - automake
    - build-essential
    - cmake
    - git
    - libass-dev
    - libfreetype6-dev
    - libmp3lame-dev
    - libopus-dev
    - libtheora-dev
    - libtool
    - libvorbis-dev
    - libx264-dev
    - mercurial
    - pkg-config
    - texinfo
    - yasm
    - zlib1g-dev
  tags:
    - apt

- name: Create sources directory
  file: path={{ sources_path }} state=directory mode=0755

# H.265/HEVC
- name: Get x265 source code
  hg: repo=https://bitbucket.org/multicoreware/x265 dest={{ sources_path }}/x265
  register: x265_source_download

- name: Build and install x265
  shell: |
    cd {{ sources_path }}/x265/build/linux && \
    cmake -G "Unix Makefiles" -DENABLE_SHARED:bool=off ../../source && \
    make && \
    make install && \
    make clean
  tags: ['compile']
  when: x265_source_download.changed and recompile_ffmpeg
  register: install_x265
  failed_when: "'FAILED' in install_x265.stderr"

# fdc-aac
- name: Get fdk-aac source code
  git: repo=git://github.com/mstorsjo/fdk-aac.git dest={{ sources_path }}/fdk-aac version={{ fdk_aac_version|default('HEAD') }}
  register: fdk_aac_source_download

- name: Build fdk-aac
  shell: |
    cd {{ sources_path }}/fdk-aac && \
    autoreconf -fiv && \
    ./configure --disable-shared && \
    make && \
    make install && \
    make distclean
  tags: ['compile']
  when: fdk_aac_source_download.changed and recompile_ffmpeg

# libvpx
- name: Get libvpx source code
  git: repo=https://chromium.googlesource.com/webm/libvpx dest={{ sources_path }}/libvpx version={{ libvpx_version|default('HEAD') }}
  register: libvpx_source_download

- name: Build and install libvpx
  shell: |
    cd {{ sources_path }}/libvpx && \
    ./configure --disable-examples --disable-unit-tests && \
    make && \
    make install && \
    make clean
  tags: ['compile']
  when: libvpx_source_download.changed and recompile_ffmpeg

# ffmpeg
- name: Get ffmpeg source code
  git: repo=git://source.ffmpeg.org/ffmpeg dest={{ sources_path }}/ffmpeg version={{ ffmpeg_version|default('HEAD') }}
  register: ffmpeg_source_download

- name: Build and install ffmpeg
  shell: |
    cd {{ sources_path }}/ffmpeg && \
    ./configure \
    --pkg-config-flags="--static" --enable-gpl --enable-libass \
    --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame \
    --enable-libopus --enable-libtheora --enable-libvorbis \
    --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
    make && \
    make install && \
    make distclean && \
    hash -r
  tags: ['compile']
  when: recompile_ffmpeg and (ffmpeg_source_download.changed or x265_source_download.changed or libvpx_source_download.changed or fdk_aac_source_download.changed)
  #when: ffmpeg_source_download.changed and x265_source_download.changed and libvpx_source_download.changed and fdk_aac_source_download.changed
