# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaenpagina',
            name='margen',
            field=models.CharField(blank=True, choices=[(None, 'Autom\xe1tico'), ('0', 'Sin margen'), ('10', '10%'), ('20', '20%'), ('30', '30%')], default=None, max_length=64, null=True, verbose_name='margen'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='margen',
            field=models.CharField(blank=True, choices=[(None, 'Autom\xe1tico'), ('0', 'Sin margen'), ('10', '10%'), ('20', '20%'), ('30', '30%')], default=None, max_length=64, null=True, verbose_name='margen'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='margen',
            field=models.CharField(blank=True, choices=[(None, 'Autom\xe1tico'), ('0', 'Sin margen'), ('10', '10%'), ('20', '20%'), ('30', '30%')], default=None, max_length=64, null=True, verbose_name='margen'),
        ),
        migrations.AlterField(
            model_name='video',
            name='margen',
            field=models.CharField(blank=True, choices=[(None, 'Autom\xe1tico'), ('0', 'Sin margen'), ('10', '10%'), ('20', '20%'), ('30', '30%')], default=None, max_length=64, null=True, verbose_name='margen'),
        ),
        migrations.AlterField(
            model_name='videoenpagina',
            name='margen',
            field=models.CharField(blank=True, choices=[(None, 'Autom\xe1tico'), ('0', 'Sin margen'), ('10', '10%'), ('20', '20%'), ('30', '30%')], default=None, max_length=64, null=True, verbose_name='margen'),
        ),
    ]
